CREATE TABLE CartItems (
Id SERIAL  PRIMARY KEY,
    CartId VARCHAR(100) NOT NULL,  
    ItemId VARCHAR(100) NOT NULL, 
    ItemQuantity INT, 
    ItemCost DOUBLE PRECISION
);

CREATE TABLE UserCart(
Id SERIAL PRIMARY KEY,
UserId VARCHAR(100) NOT NULL,
CartId VARCHAR(100) NOT NULL
);