name: Build and Test Projects
on:
    push: 
        branches: ["master"]

jobs:
    build_and_test_solution:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout
            uses: actions/checkout@v2

        -   name: Setup .NET
            uses: actions/setup-dotnet@v1
            with:
                dotnet-version: '6.x'

        -   name: Restore Dependencies
            run: dotnet restore

        -   name: Build
            run: dotnet build --configuration Release

        -   name: Test
            run: dotnet test

          
  
                
            