name: Detect Changes in Services

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/BuildingBlocks/**'
      - 'src/Services/**'
      - 'src/Shared/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run Step 1
        run: | 
    
            docker login -u "${{ secrets.DOCKER_USERNAME }}" --password ${{ secrets.DOCKER_PASSWORD }}

            docker build . -t ecommerce/catalogservice:v1 -f src/Services/Ecommerce.Catalog.API/Dockerfile
            docker push ecommerce/catalogservice:v1
            echo "Build and pushed ecommerce/catalogservice:v1"

            docker build . -t ecommerce/accountservice:v1 -f src/Services/Ecommerce.Account.API/Dockerfile
            docker push ecommerce/accountservice:v1
            echo "Build and pushed ecommerce/accountservice:v1"

            docker build . -t ecommerce/cartservice:v1 -f src/Services/Ecommerce.Cart.API/Dockerfile
            docker push ecommerce/cartservice:v1
            echo "Build and pushed ecommerce/cartservice:v1"

            docker build . -t ecommerce/identityservice:v1 -f src/Services/Ecommerce.Identity.API/Dockerfile
            docker push ecommerce/identityservice:v1
            echo "Build and pushed ecommerce/identityservice:v1"
