name: Detect Changes in Services

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/BuildingBlocks/**'
      - 'src/Services/**'
      - 'src/Shared/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run Step 1
        if: ${{ contains(github.event_paths, 'src/BuildingBlocks/**') || contains(github.event_paths, 'src/Services/Ecommerce.Cart.API/**') }}
        run: echo "Running Step 1 because changes detected in 'src/BuildingBlocks/**'"

      - name: Run Step 2
        if: ${{ contains(github.event.head_changes, 'src/Services/Ecommerce.Account.API/**') }}
        run: echo "Running Step 2 because changes detected in 'src/Services/Ecommerce.Account.API/**'"

      - name: Run Step 3
        if: ${{ contains(github.event_paths, 'src/Services/Ecommerce.Catalog.API/**') }}
        run: echo "Running Step 3 because changes detected in 'src/Services/Ecommerce.Catalog.API/**'"

      - name: Run Step 4
        if: ${{ contains(github.event_paths, 'src/Services/Ecommerce.Identity.API/**') }}
        run: echo "Running Step 4 because changes detected in 'src/Services/Ecommerce.Identity.API/**'"

      - name: Run Step 5
        if: ${{ contains(github.event_paths, 'src/Services/Ordering/**') }}
        run: echo "Running Step 5 because changes detected in 'src/Services/Ordering/**'"

      - name: Run Step 6
        if: ${{ contains(github.event_paths, 'src/Shared/**') }}
        run: echo "Running Step 6 because changes detected in 'src/Shared/**'"

