name: Push Images to docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/BuildingBlocks/**'
      - 'src/Services/**'
      - 'src/Shared/**'
      - '.github/workflows/docker-deploy.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Images
        run: | 
            docker build . -t projectsofjoel/ecommerce-catalogservice:v1 -f src/Services/Ecommerce.Catalog.API/Dockerfile
            docker push projectsofjoel/ecommerce-catalogservice:v1
            echo "Build and pushed projectsofjoel/ecommerce-catalogservice:v1"

            docker build . -t projectsofjoel/ecommerce-accountservice:v1 -f src/Services/Ecommerce.Account.API/Dockerfile
            docker push projectsofjoel/ecommerce-accountservice:v1
            echo "Build and pushed projectsofjoel/ecommerce-accountservice:v1"

            docker build . -t projectsofjoel/ecommerce-cartservice:v1 -f src/Services/Ecommerce.Cart.API/Dockerfile
            docker push projectsofjoel/ecommerce-cartservice:v1
            echo "Build and pushed projectsofjoel/ecommerce-cartservice:v1"

            docker build . -t projectsofjoel/ecommerce-identityservice:v1 -f src/Services/Ecommerce.Identity.API/Dockerfile
            docker push projectsofjoel/ecommerce-identityservice:v1
            echo "Build and pushed projectsofjoel/ecommerce-identityservice:v1"

            docker build . -t projectsofjoel/ecommerce-orderingservice:v1 -f src/Services/Ordering/Ecommerce.Orders.API/Dockerfile
            docker push projectsofjoel/ecommerce-orderingservice:v1
            echo "Build and pushed projectsofjoel/ecommerce-orderingservice:v1s"
